# Generated by Django 3.2.3 on 2023-05-05 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('purchase_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('logo', django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 400], upload_to='theater_logos')),
                ('no_of_seat_rows', models.IntegerField(default=10)),
                ('num_of_seats_column', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('theater_name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Upcomming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(default='default.jpg', upload_to='upcomming_poster')),
                ('genre', models.CharField(max_length=50, null=True)),
                ('cast', models.CharField(max_length=200, null=True)),
                ('directed_by', models.CharField(max_length=50, null=True)),
                ('upload_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_movies', to='movie_sys.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Ott',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(default='default.jpg', upload_to='Ott_poster')),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('cast', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('movie_video', models.FileField(upload_to='ott_movie_videos/')),
                ('trailer_video', models.FileField(blank=True, null=True, upload_to='ott_movie_trailer/')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(default='default.jpg', upload_to='movie_poster')),
                ('releasing_date', models.DateField()),
                ('genre', models.CharField(max_length=50, null=True)),
                ('cast', models.CharField(max_length=200, null=True)),
                ('directed_by', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ticket_price', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('booked_seats', models.ManyToManyField(blank=True, to='movie_sys.Booking')),
                ('theater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie_sys.theater')),
            ],
        ),
    ]
