# Generated by Django 3.2.3 on 2023-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='contact',
            field=models.IntegerField(default=9807654321),
        ),
    ]
