# Generated by Django 3.2.3 on 2023-04-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0002_seat_reserved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='reserved',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='selected_seats',
        ),
    ]
