# Generated by Django 3.2.3 on 2023-05-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0004_alter_movie_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_no',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_column',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_row',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='reserved_seats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
