# Generated by Django 3.2.3 on 2023-05-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0004_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='column',
            new_name='seat_column',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='row',
            new_name='seat_row',
        ),
    ]
