# Generated by Django 3.2.3 on 2023-05-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0005_auto_20230527_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='booked_seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_sys.movie'),
        ),
    ]
