# Generated by Django 3.2.3 on 2023-05-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0005_auto_20230502_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_no',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
