# Generated by Django 3.2.3 on 2023-05-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0007_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
