# Generated by Django 3.2.3 on 2023-05-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0009_alter_booking_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='offer',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
