# Generated by Django 3.2.3 on 2023-05-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0010_auto_20230503_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_sys.theater'),
        ),
    ]
