# Generated by Django 3.2.3 on 2023-06-17 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0010_alter_movie_screening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='airing_time',
            field=models.DateTimeField(default="2023-06-16 12:00:00"),
        ),
    ]
