# Generated by Django 3.2.3 on 2023-05-04 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0011_booking_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_of_rows',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='booked_seats',
            field=models.ManyToManyField(blank=True, to='movie_sys.Booking'),
        ),
        migrations.AddField(
            model_name='movie',
            name='offer',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='ticket_price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_no',
            field=models.IntegerField(),
        ),
    ]
