# Generated by Django 3.2.3 on 2023-06-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0011_movie_airing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='airing_time',
            field=models.DateTimeField(default='12:00 AM'),
        ),
    ]
