# Generated by Django 3.2.3 on 2023-06-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0012_alter_movie_airing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='airing_time',
        ),
    ]
