# Generated by Django 3.2.3 on 2023-05-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0012_auto_20230504_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='theater',
            new_name='theater_name',
        ),
    ]
