# Generated by Django 3.2.3 on 2023-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0014_rename_theater_name_movie_theater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ott',
            options={'permissions': [('can_view_ott', 'Can view Ott')]},
        ),
        migrations.AddField(
            model_name='ott',
            name='movie_video',
            field=models.FileField(default='default.jpg', upload_to='ott_movie_videos/'),
        ),
        migrations.AddField(
            model_name='ott',
            name='trailer_video',
            field=models.FileField(null=True, upload_to='ott_movie_trailer/'),
        ),
    ]
