# Generated by Django 3.2.3 on 2023-06-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0014_seatreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatReservation',
        ),
    ]
