# Generated by Django 3.2.3 on 2023-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0015_auto_20230504_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott',
            name='movie_video',
            field=models.FileField(upload_to='ott_movie_videos/'),
        ),
    ]
