# Generated by Django 3.2.3 on 2023-06-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0016_auto_20230617_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='screening_datetime',
            new_name='screening_time',
        ),
    ]
