# Generated by Django 3.2.3 on 2023-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0016_alter_ott_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott',
            name='cast',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ott',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ott',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
