# Generated by Django 3.2.3 on 2023-06-17 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0017_rename_screening_datetime_movie_screening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screening_time',
            field=models.TimeField(default=datetime.datetime(2023, 6, 17, 13, 0, tzinfo=utc)),
        ),
    ]
