# Generated by Django 3.2.3 on 2023-06-20 02:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0019_auto_20230617_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screening_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 7, 15, tzinfo=utc)),
        ),
    ]
