# Generated by Django 3.2.3 on 2023-07-01 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0020_alter_movie_screening_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screening_datetime2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='screening_datetime3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screening_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 7, 15, tzinfo=utc)),
        ),
    ]
