# Generated by Django 3.2.3 on 2023-07-22 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0022_auto_20230704_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screening_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 7, 15, tzinfo=utc)),
        ),
    ]
