# Generated by Django 3.2.3 on 2023-05-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0023_alter_ott_upload_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ott',
            name='upload_by',
        ),
    ]
