# Generated by Django 3.2.3 on 2023-05-04 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_sys', '0024_remove_ott_upload_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='upload_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ott',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
