# Generated by Django 3.2.3 on 2023-08-16 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_sys', '0026_auto_20230816_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking3',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='booking3',
            unique_together={('movie', 'seat_row', 'seat_column')},
        ),
    ]
