# Generated by Django 3.2.3 on 2023-05-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0026_auto_20230504_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ott',
            name='upload_by',
        ),
    ]
