# Generated by Django 3.2.3 on 2023-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0027_auto_20230816_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking3',
            name='seat_column',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
