# Generated by Django 3.2.3 on 2023-08-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0029_auto_20230817_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_video',
            field=models.FileField(default="{% static 'photos/cinemalogo.png' %}", upload_to='movie_trailer/'),
        ),
    ]
