# Generated by Django 3.2.3 on 2023-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0032_alter_movie_trailer_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_video',
            field=models.FileField(default='404Error.png', upload_to='movie_trailer_video/'),
        ),
    ]
