# Generated by Django 3.2.3 on 2023-05-05 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_sys', '0032_rename_ott_otts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Otts',
            new_name='Ott',
        ),
    ]
