# Generated by Django 3.2.3 on 2023-08-17 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_sys', '0035_booking3_selected_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_screening',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking2',
            name='selected_screening',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_column',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_row',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking2',
            name='seat_column',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='booking2',
            name='seat_row',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('movie', 'seat_row', 'seat_column')},
        ),
        migrations.AlterUniqueTogether(
            name='booking2',
            unique_together={('movie', 'seat_row', 'seat_column')},
        ),
    ]
