# Generated by Django 3.2.3 on 2023-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0036_auto_20230817_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screening_datetime2',
            field=models.DateTimeField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screening_datetime3',
            field=models.DateTimeField(default=0, null=True),
        ),
    ]
