# Generated by Django 3.2.3 on 2023-08-23 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0037_auto_20230817_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screening_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 7, 15, tzinfo=utc)),
        ),
    ]
