# Generated by Django 3.2.3 on 2023-08-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0043_auto_20230824_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking2',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking3',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
