# Generated by Django 3.2.3 on 2023-09-19 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sys', '0044_auto_20230824_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screening_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 7, 15, tzinfo=utc)),
        ),
    ]
