# Generated by Django 3.2.3 on 2023-08-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
