# Generated by Django 3.2.3 on 2023-09-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
    ]
