# Generated by Django 3.2.3 on 2023-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_profile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], default='false', max_length=5),
        ),
    ]
